addons:
  apt:
    packages:
    - oracle-java8-installer
language: clojure
lein: 2.7.1
os:
- linux
env:
  global:
  - secure: VwBtOjsYrQCPabvvX9TM7qKvt2QdLMrKSj41vzoNsQpmiDPvARocCf+ScaPnEwmVSjHqLJrHsG1ZwyJfFyQPzvqTCNajaYdaS6FQl/6lGDEICe9DiVhdVqEVp4CoIMa+f71v6t8kjJ8Jf6MFnQXadzUd1XbvDjU1I5asfuUOy1uYQGSfKijstkL3IqKVkcve22bEpRDcTHiuMWdwXuoaB4NOut0sGWW1/HKVONdrAOUtqr0zm2RWqEsCmyV/e9P16JFNNsjBEjYP5I5DRqnomHRekiIbyWgLNJ3o6OHiMXz6A1yFejO0Eq2CQ2znLpVN9y8q/K+CwSxMOexvMAsOPu556rQ7GZJWFzqcofa3R7w9zuix/oIlOwYouIIPhm/eyy8lDzOxwWYz9F3TdFN2rabZ+gUIkC1yCPArlhrt6hRx2sduyVkYA0w1xrDkBU8q0FgCcCaxqYsjo2rYyt2TND7bnsGZbdsrxZdDcpt6IS/0Ug56dnbYUGX9Dv/EFae/QQQI9Uyt1pn4QtxAMz+BcnhEJ2TEadgs4kQu1+hc8TU4C+b7+xbbku5TUQi+rd6jKrfig31mCSDViV+nKBn4PJQHlGThbNdermB/1quGxxIZKdljuAP+ARBVCxMLi7kj+zSBADG+FjdxGvqDGkc+4rjGqKdr/7Z64HJmXCH815A=
  - secure: oXmyFYkc0hI8/q8bcnNjWhY4nwh7ha5XDHk+8PooOZBvfy8QdJgcsTc4QQ4LfhLXSMmG9uK3lqWy5it6bVbkJRNaFfSxldn/O+wuzy9ORQO2c2M6aH5COPr++frkQcbbWwfxoPq4aS5bYuYLcey9CbzPav/ZPd8vkfjjBA4csuW/5rSEWh9ADZutICQcS/Lyb7qt8vjbzCXfXJe1f5UtvJAC1DW/PRKDyvgfG2eIiMy9KusfX6HZoZL2lct3YAgN8NDowrA6s+an1JPi3dr7TMC5ONcj0BjP1Awv2XCYpt1LiHAhlV/iqbmEJdTCc+lteZ1eVzVIoZmavVNvo9KqExUR1NmzFzq81FqZM9CcYVeq6ldeijqjVDOH+W0S327cB1lVL/O1I8Tt8tAQJh0KU2ZvqAG7pqKkl7xLQLpC5v344P6M8IijByPt4uNvVNUGld7aswQigjazJh9tUCkFQl6LMLcJ0gYEiwARG8kklkhijG104ZxkHtLu5yN5qGSzyZdcTmAdmiq0E+PHirMhqwTFy+PG935kD6HHtvJ4ejelPjeEwYr0Kyiabx4PZuWzY2ypy0Men96NzJca2sATwPHY7qS5GBaZR66JcfemyeXDVGDkJ25gSKuBw5k/s+L8GENCh2+ShFXgF7YeuQ64QJcw1mPUE+oTkk8Kg6OmFe8=
